server:
  port: 8082

spring:
  # redis
  redis:
    host: 172.25.144.179
    port: 6379
    database: 0
  # 数据源
  datasource:
    url: jdbc:mysql://172.25.144.179/vhr?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 3152903564wanyouli@qq.com
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 日期格式化
  mvc:
    date-format: yyyy-MM-dd
  # session集群
  session:
    store-type: redis
  # 邮件服务
  mail:
    username: 13049394389@163.com # abananawolf@qq.com
    password: WXNJLIHYZYZNLGZM # iihrkemmkvblddge
    host: smtp.163.com # smtp.qq.com
  # rabbitmq
  rabbitmq:
    username: guest
    password: guest
    host: 172.25.144.179
    port: 5672
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        prefetch: 1
        concurrency: 1
        max-concurrency: 5
        acknowledge-mode: manual
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1500ms
          max-interval: 2000ms
          max-attempts: 3
    template:
      mandatory: true
      retry:
        enabled: false
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
logging:
  config: classpath:logback-spring-linux-prod.xml